name: Build and Package

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
        package-type: [ 'jar', 'war' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure packaging
        run: |
          if [ "${{ matrix.package-type }}" == "war" ]; then
            echo "ACTIVE_PROFILE=war-profile" >> $GITHUB_ENV
          fi

      - name: Build with Maven
        run: mvn -B clean package -DskipTests -P${{ env.ACTIVE_PROFILE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package-type }}-${{ github.run_id }}
          path: target/*.${{ matrix.package-type }}
          if-no-files-found: error
          retention-days: 7

  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Show artifacts
        run: |
          echo "Generated artifacts:"
          echo "${{ needs.build.outputs.artifact-urls }}"
